/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import BusinessLogic.*;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Login extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Login
     */
    
    UsersDAO userdb;
    UserBL user;
    
    JPanel jp ;
    int width=this.getToolkit().getScreenSize().width;
    int height = this.getToolkit().getScreenSize().height;
    
    public Login() {
        initComponents();
        setPositions();
        userdb = new UsersDAO();
        //repaint();
    }

    void setPositions()
    {
        
        this.setBounds(0,0 ,this.getToolkit().getScreenSize().width ,this.getToolkit().getScreenSize().width );
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        jp = new JPanel();
        System.out.println(this.getBounds());
        jp.setBounds(this.getBounds());
        this.add(jp);
        jp.setBackground(new Color(3,20 ,38));
        
        System.out.println(width+" : "+height);
        jTextField1.setText("");
        jTextField2.setText("");
       jTextField1.setBackground(new Color(3,20 ,38));
       jTextField1.setForeground(Color.WHITE);
       jLabel4.setLocation((width/2)-70,200);
      // jTextField1.setLocation((width/2)-75,(height/2)-jTextField1.getHeight());
       jLabel1.setLocation((width/2)-165,(height/2)-190);
       jLabel2.setLocation((width/2)-165,(height/2)-95);
     //  jLabel1.setLocation((width/2)-125,(height/2)-jTextField1.getHeight() );
        jTextField1.setBounds((width/2)-90,(height/2)-180,300,50);
        jTextField2.setBounds((width/2)-90,(height/2)-85,300,50);
      // jTextField2.setLocation((width/2)-75,((height+90)/2)-jTextField1.getHeight());
      // jLabel2.setLocation((width/2)-120,((height+90)/2)-jTextField1.getHeight());
       jButton1.setLocation((width/2)-5,((height+180)/2)-jTextField1.getHeight());
        //jTextField1.setBounds(700, 350, 100, 50);
        jTextField2.setBackground(new Color(3,20 ,38));
        jTextField2.setForeground(Color.WHITE);
        
        jLabel3.setLocation(width-100,50);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 120, 270, 30);

        jButton1.setBackground(new java.awt.Color(1, 185, 225));
        jButton1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 270, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 100, 70, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/entering-password (1).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 180, 80, 80);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/close.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 10, 70, 70);

        jLabel4.setFont(new java.awt.Font("Blankblizzkrieg", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SOUVENIR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 20, 280, 70);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(300, 200, 270, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        userdb = null;
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name =userdb.validateUser(jTextField1.getText(), jTextField2.getText());
        
        //String name = userdb.validateUser("shahumang19@gmail.com", "abcd1");
        
        if(name != "")
        {
            user = new UserBL(name, jTextField1.getText(), jTextField2.getText());
            JOptionPane.showMessageDialog(this, "Welcome "+name);
            HomeScreen hm = new HomeScreen(user);
            hm.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid Credentials", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
