package Final;

import BusinessLogic.NoteBL;
import BusinessLogic.NoteDAO;
import BusinessLogic.UserBL;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.TrayIcon.MessageType;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin1
 */
public class Notes_create extends javax.swing.JFrame {

    NoteBL noteUnderUse;
    NoteDAO nd;
    UserBL userHere;
    boolean isNew = false;

    /**
     * Creates new form Notes
     */
    public Notes_create(int Noteid, UserBL userHere) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        int width = this.getToolkit().getScreenSize().width;
        int height = this.getToolkit().getScreenSize().height;
        Color_selection cs = new Color_selection();
        cs.setVisible(true);
        cs.setBounds(483, 656, 322, 50);
        this.userHere = userHere;
        jPanel1.add(cs);
        jLabel7.setLocation(20, 50);
        jLabel8.setLocation(width - 100, 50);
        jScrollPane1.setBounds(270, 100, 1350, 860);
        jLabel2.setLocation(270, 975);
        jLabel3.setLocation(330, 975);
        jLabel4.setLocation(390, 975);
        jLabel5.setLocation(450, 975);
        jLabel6.setLocation(510, 975);
        jLabel9.setLocation(570, 975);
        jLabel10.setLocation(630, 975);
        nd = new NoteDAO();
        noteUnderUse = nd.readNote(Noteid);
        jTextPane1.setText(noteUnderUse.getTextData());
        isNew = false;
    }

    public Notes_create(UserBL userHere) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        int width = this.getToolkit().getScreenSize().width;
        int height = this.getToolkit().getScreenSize().height;
        this.userHere = userHere;
        Color_selection cs = new Color_selection();
        cs.setVisible(true);
        cs.setBounds(483, 656, 322, 50);
        jPanel1.add(cs);
        jLabel7.setLocation(20, 50);
        jLabel8.setLocation(width - 100, 50);
        jScrollPane1.setBounds(270, 100, 1350, 860);
        jLabel2.setLocation(270, 975);
        jLabel3.setLocation(330, 975);
        jLabel4.setLocation(390, 975);
        jLabel5.setLocation(450, 975);
        jLabel6.setLocation(510, 975);
        jLabel9.setLocation(570, 975);
        jLabel10.setLocation(630, 975);
        nd = new NoteDAO();
        NoteBL newNote = new NoteBL();
        newNote.setId(nd.generateNewID());
        newNote.setCat("");
        newNote.setTitle("");
        newNote.setTextData("");
        newNote.setPriority(1);
        newNote.setLock(false);
        newNote.setCreationDate(Date.valueOf(LocalDate.now()));
        newNote.setCreationTime(Time.valueOf(LocalTime.now()));
        noteUnderUse = newNote;
        isNew = true;
    }

    private Notes_create() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        g.setColor(Color.white);
        g.drawRoundRect(200, 50, 1500, 1000, 30, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(3, 20, 38));
        jPanel1.setLayout(null);

        jTextPane1.setContentType("text/html"); // NOI18N
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 164, 760, 486);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(893, 697, 80, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1_1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 130, 50, 49);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1_2_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 660, 50, 49);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1_3_1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 660, 50, 49);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1_4_1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 660, 50, 49);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/1_5.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 660, 45, 49);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/back.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 30, 70, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/close.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1070, 30, 70, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lock.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 200, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/delete.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 270, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (isNew) {
            noteUnderUse.setTextData(jTextPane1.getText());
            if (nd.insertNote(noteUnderUse, userHere.getEmail())) {
                JOptionPane.showMessageDialog(this, "Note Created !");
                isNew = false;
            }
        } else {
            noteUnderUse.setTextData(jTextPane1.getText());
            if (nd.updateNote(noteUnderUse)) {
                JOptionPane.showMessageDialog(this, "Note Updated !");
            }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        int strt=0,nd=0;
        
        strt = jTextPane1.getSelectionStart();
        nd = jTextPane1.getSelectionEnd();
        String s1 ="<b>"+ jTextPane1.getSelectedText() +"</b>";
        System.out.println(s1);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s1));
        jTextPane1.select(strt, nd);
        
        String s2 ="<i>"+ jTextPane1.getSelectedText() +"</i>";
        System.out.println(s2);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s2));
        jTextPane1.select(strt, nd);

        String s3 ="<u>"+ jTextPane1.getSelectedText() +"</u>";
        System.out.println(s3);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s3));
        jTextPane1.select(strt, nd);

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (noteUnderUse.isLock()) {
            noteUnderUse.setLock(false);
            if (nd.updateNote(noteUnderUse)) {
                JOptionPane.showMessageDialog(this, "Note Unlocked !");
            }
        } else {
            noteUnderUse.setLock(true);
            if (nd.updateNote(noteUnderUse)) {
                JOptionPane.showMessageDialog(this, "Note Locked !");
            }
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int strt=0,nd=0;
        
        strt = jTextPane1.getSelectionStart();
        nd = jTextPane1.getSelectionEnd();
        String s1 ="<b>"+ jTextPane1.getSelectedText() +"</b>";
        System.out.println(s1);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s1));
        jTextPane1.select(strt, nd);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int strt=0,nd=0;
        
        strt = jTextPane1.getSelectionStart();
        nd = jTextPane1.getSelectionEnd();
        String s1 ="<i>"+ jTextPane1.getSelectedText() +"</i>";
        System.out.println(s1);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s1));
        jTextPane1.select(strt, nd);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int strt=0,nd=0;
        
        strt = jTextPane1.getSelectionStart();
        nd = jTextPane1.getSelectionEnd();
        String s1 ="<u>"+ jTextPane1.getSelectedText() +"</u>";
        System.out.println(s1);
        jTextPane1.setText(jTextPane1.getText().replace(jTextPane1.getSelectedText(), s1));
        jTextPane1.select(strt, nd);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        if (isNew) {
            Notes n1 = new Notes(userHere);
            n1.setVisible(true);
            this.dispose();
        } else {
            if (nd.deleteNote(noteUnderUse, userHere.getEmail())) {
                JOptionPane.showMessageDialog(this, "Note Deleteted !");
                Notes n1 = new Notes(userHere);
                n1.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notes_create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
